'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class CategoryManager

        '''<summary>
        '''hidOpenImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidOpenImage As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ddlParent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlParent As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''litErrorMessageTop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessageTop As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''litErrorMessageBottom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessageBottom As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
