'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class ItemManagerPricing

        '''<summary>
        '''litDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDebug As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hidCurrentPackageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPackageID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hidCurrentVendorPackageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentVendorPackageID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''litCurrentPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCurrentPrice As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litItemID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptPackage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPackage As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''divVendorPackage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divVendorPackage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litPackageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPackageID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litVendorPackageUpdateError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litVendorPackageUpdateError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptVendorPackage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptVendorPackage As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''divPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPrice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litPriceVendorPackageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPriceVendorPackageID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPrice As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''btnReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReturn As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
