'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class OrderManager

        '''<summary>
        '''txtFobNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFobNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlFobClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFobClient As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFobType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFobType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnFobOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFobOrder As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''odsClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsClients As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''OrderList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderList1 As Global.sselStore.Controls.OrderList
    End Class
End Namespace
