'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin
    
    Partial Public Class UserLabel
        
        '''<summary>
        '''ddlUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUsers As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblUserFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserFirstName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblUserLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserLastName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlAccounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAccounts As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblExternalInternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExternalInternal As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblStaff control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStaff As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlAllManagers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAllManagers As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlOrgs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOrgs As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
