'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

    Partial Public Class CartView

        '''<summary>
        '''lblTopMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTopMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gvCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvCart As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnAdjustQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdjustQ As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divCartOperation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCartOperation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStockError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStockError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnContinueShopping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnContinueShopping As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCheckout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCheckout As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
