'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class CatalogList
        
        '''<summary>
        '''litSecItemMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSecItemMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''dlItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlItem As Global.System.Web.UI.WebControls.DataList
        
        '''<summary>
        '''odsRootCategoryList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsRootCategoryList As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''odsSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsSearch As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
