'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

    Partial Public Class OrderDetail

        '''<summary>
        '''litError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''divMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidSOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSOID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hidClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidClientID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lbtnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnBack As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblSOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSOID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divOrderHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOrderHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtCreationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreationDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''spnStatusDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnStatusDDL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''spnStatusText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnStatusText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClient As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContact As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtStatusChangeDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStatusChangeDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CartView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartView1 As Global.sselStore.Controls.CartView

        '''<summary>
        '''lblSaveMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSaveMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divAddNewItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAddNewItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtNewItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewItemID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvNewItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvNewItemID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revNewItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revNewItemID As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''txtNewQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewQty As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvNewQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvNewQty As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revNewQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revNewQty As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''btnCreateNewOrderDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCreateNewOrderDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''sum2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sum2 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''panSecurityItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panSecurityItems As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rptSecItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptSecItems As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''spnPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnPrint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPrint As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkPrinter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPrinter As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblLastStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastStatus As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
