'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class OrderList
        
        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''odsStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsStatus As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''spnPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnPrint As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''gvStoreOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvStoreOrder As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''odsOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsOrders As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''odsOrdersAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsOrdersAdmin As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
